--MYSALARY TABLE[dbo].[MYSALARY]

--AGREGATE FUNCTIONS

USE AdventureWorks2017
SELECT * FROM [MYSALARY]

SELECT AVG(SALARY)
FROM MYSALARY

SELECT COUNT(SALARY)
FROM MYSALARY

SELECT * FROM MYSALARY

SELECT SUM(SALARY)
FROM MYSALARY

SELECT MIN(SALARY)
FROM MYSALARY

SELECT MAX(SALARY)
FROM MYSALARY

--STRING FUNCTION
--USE MYORDERTABLE[dbo].[MYORDER]

SELECT * FROM MYORDER

--CONCATENATE 2 STRINGS USE CONCAT
PRINT CONCAT('STRING1','STRING2')

SELECT ORDERID, ORDERNAME, CONCAT('ORDERNAME',' ','ORDERNAME') AS JUVORDERNAME
FROM MYORDER

SELECT ORDERID, ORDERNAME, CONCAT('ORDERNAME',' ',RAND()) AS JUVORDERNAME
FROM MYORDER

--EXTRACTING DATA FROM A STRING
--LEFT FUNCTION
SELECT ORDERID,ORDERNAME, LEFT(ORDERNAME,5) AS CHARACTERS
FROM MYORDER

SELECT ORDERID,ORDERNAME, RIGHT(ORDERNAME,5) AS CHARACTERS
FROM MYORDER

--SUBSTRINGS JUST PART OF A WORD STARTING WITH A CHARACTER NUMBER SPECIFIED

SELECT ORDERID,ORDERNAME, SUBSTRING(ORDERNAME,2,5) AS PARTORDER
FROM MYORDER

--lOWER, uPPER CASE
SELECT ORDERID,ORDERNAME, LOWER(ORDERNAME) AS LOWERCASE
FROM MYORDER

SELECT ORDERID,ORDERNAME, UPPER(ORDERNAME) AS LOWERCASE
FROM MYORDER

--LENGTH OF A STRING
SELECT ORDERID,ORDERNAME, LEN(ORDERNAME) AS LOWERCASE
FROM MYORDER

SELECT ORDERID,ORDERNAME,CONCAT(UPPER(LEFT(ORDERNAME,1)),LOWER(SUBSTRING(ORDERNAME,2,LEN(ORDERNAME))))
FROM MYORDER

--TRIM FUNCTION

SELECT '  MYFUNCTION  '

SELECT LEN('  MYFUNCTION  ')
--LTIM FUNCTION

SELECT LTRIM('  MYFUNCTION  ')

--RTRIM
SELECT RTRIM('  MYFUNCTION  ')
--REMOVE FROM BOTH SIDES IS

SELECT RTRIM(LTRIM('  MYFUNCTION  '))