USE DSTRAINING
GO

SELECT * FROM [dbo].[OrderBreakdown]
WHERE (
	CATEGORY = 'FURNITURE'
	AND
	CONVERT(FLOAT,[SALES]) > 100
	)
OR
CATEGORY ='TECHNOLOGY'

SELECT * FROM  [dbo].[OrderBreakdown1]
WHERE CATEGORY = 'TECHNOLOGY'
AND 
CONVERT(FLOAT,[SALES]) > 100

SELECT * FROM [dbo].[OrderBreakdown]
WHERE CONVERT(FLOAT,PROFIT)<0
AND
[CATEGORY] = 'FURNITURE'
AND 
[SUB-CATEGORY] = 'CHAIRS'
ORDER BY [PROFIT]

SELECT * FROM [dbo].[ListOfOrders]
WHERE [ORDER ID] LIKE 'BN%'

SELECT * FROM [dbo].[ListOfOrders]
WHERE [COUNTRY] LIKE '%E%'

SELECT * FROM [dbo].[ListOfOrders]
WHERE [SHIP MODE] = 'ECONOMY'

SELECT * FROM [dbo].[ListOfOrders]
WHERE (
[ORDER ID] LIKE 'AZ-2011%'
AND [STATE] = 'ENGLAND'
AND [CITY] = 'LONDON'
)