--JOINS
CREATE TABLE MYEMPLOYEE (EMPLOYEEID INT, FIRSTNAME VARCHAR(20), LASTNAME VARCHAR(20))
INSERT INTO MYEMPLOYEE 
VALUES (1,'MICHAEL','SCOTT'),
		(2,'PAM','BEESLY'),
		(3,'DWIGHT','SCHRUTE');

SELECT * FROM MYEMPLOYEE

CREATE TABLE MYSALARY (EMPLOYEEID INT, SALARY FLOAT);

INSERT INTO MYSALARY 
VALUES              (1, 10000),
					(2, 8000),
					(3, 6000);

SELECT * FROM MYEMPLOYEE
SELECT * FROM MYSALARY
--INNER JOIN

SELECT A.FIRSTNAME,A.LASTNAME,B.SALARY
FROM MYEMPLOYEE A INNER JOIN MYSALARY B
ON A.EMPLOYEEID=B.EMPLOYEEID

--LEFT OUTER JOIN

CREATE TABLE MYPHONE(EMPLOYEEID INT, PHONENUMBER INT)

INSERT INTO MYPHONE 
VALUES (1, 177567898),
		(2, 288567895);

SELECT * FROM MYEMPLOYEE		
SELECT * FROM MYPHONE

SELECT A.FIRSTNAME,A.LASTNAME,B.PHONENUMBER
FROM MYEMPLOYEE A LEFT JOIN MYPHONE B
ON A.EMPLOYEEID=B.EMPLOYEEID

-- RIGHT JOIN

CREATE TABLE MYPARKING (EMPLOYEEID INT, PARKINGSPOT VARCHAR(20))

INSERT INTO MYPARKING
VALUES (1,'A1'),
(2,'A2'),
(3,'A3'),
(4,'A4')

SELECT * FROM MYEMPLOYEE
SELECT * FROM MYPARKING

SELECT A.PARKINGSPOT, B.FIRSTNAME, B.LASTNAME
FROM MYPARKING A RIGHT JOIN MYEMPLOYEE B
ON A.EMPLOYEEID = B.EMPLOYEEID

-- FULL OUTER JOIN

CREATE TABLE MYCUSTOMER (CUSTOMERID INT, CUSTOMERNAME VARCHAR (20))

INSERT INTO MYCUSTOMER
VALUES (1, 'RAKESH'),
		(1, 'JOHN')
		
CREATE TABLE MYORDER (ORDERID INT, ORDERNAME VARCHAR(20), CUSTOMERID INT)

INSERT INTO MYORDER
VALUES(1,'SOMEORDER1',1),
		(2,'SOMEORDER2',2),
		(3,'SOMEORDER3',7),
		(4,'SOMEORDER4',1)

SELECT * FROM MYCUSTOMER
SELECT * FROM MYORDER

SELECT A.CUSTOMERNAME,A.CUSTOMERNAME,B.ORDERID,B.ORDERNAME 
FROM MYCUSTOMER A FULL OUTER JOIN MYORDER B
ON A.CUSTOMERID=B.CUSTOMERID


