--CREATE VIEW

CREATE VIEW MYCUSTOMVIEWUS
AS
SELECT * FROM [Sales].[SalesTerritory]
WHERE [CountryRegionCode] LIKE 'US'

SELECT * FROM MYCUSTOMVIEWUS


CREATE VIEW MYNEWVIEW
AS
SELECT * FROM [Sales].[SalesTerritory]
WHERE [Name] LIKE 'NORTHEAST'

SELECT * FROM MYNEWVIEW