CREATE TABLE  "ORDERS" 
   (
    "ORD_NUM" NUMERIC(6,0) NOT NULL PRIMARY KEY, 
	"ORD_AMOUNT" NUMERIC(12,2) NOT NULL, 
	"ADVANCE_AMOUNT" NUMERIC(12,2) NOT NULL, 
	"ORD_DATE" DATE NOT NULL, 
	"CUST_CODE" VARCHAR(6) NOT NULL REFERENCES CUSTOMER, 
	"AGENT_CODE" CHAR(6) NOT NULL REFERENCES AGENTS, 
	"ORD_DESCRIPTION" VARCHAR(60) NOT NULL
   );