CREATE TABLE  "CUSTOMER" 
   (	"CUST_CODE" VARCHAR(6) NOT NULL PRIMARY KEY, 
	"CUST_NAME" VARCHAR(40) NOT NULL, 
	"CUST_CITY" CHAR(35), 
	"WORKING_AREA" VARCHAR(35) NOT NULL, 
	"CUST_COUNTRY" VARCHAR(20) NOT NULL, 
	"GRADE" NUMERIC, 
	"OPENING_AMT" NUMERIC(12,2) NOT NULL, 
	"RECEIVE_AMT" NUMERIC(12,2) NOT NULL, 
	"PAYMENT_AMT" NUMERIC(12,2) NOT NULL, 
	"OUTSTANDING_AMT" NUMERIC(12,2) NOT NULL, 
	"PHONE_NO" VARCHAR(17) NOT NULL, 
	"AGENT_CODE" CHAR(6) NOT NULL REFERENCES AGENTS
); 