/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (5000) [ROWNR]
      ,[ID]
      ,[Prefix]
      ,[Name]
      ,[Surname]
      ,[CityPref]
      ,[City]
      ,[State]
      ,[CountryCode]
      ,[Wording]
      ,[Country_1]
      ,[Latitude]
      ,[Longitude]
      ,[Phone]
      ,[Date]
      ,[Email]
      ,[Card]
      ,[CardNumber]
      ,[ISBN]
  FROM [DSTRAINING].[dbo].[JUVFAKE]