----create procedure 
 CREATE PROCEDURE JUVPROCEDURE
 AS
 SET NOCOUNT ON
 SELECT * FROM [HumanResources].[Shift]

 EXECUTE [dbo].[JUVPROCEDURE]

 CREATE PROCEDURE IZAEXTRACT
 AS
 SET NOCOUNT ON
 SELECT * FROM [Production].[PRODUCT_2]

 EXECUTE [dbo].[IZAEXTRACT]

 ----WITH NOCOUNT OFF

  CREATE PROCEDURE JUVPROCEDURE2
 AS
 SET NOCOUNT OFF
 SELECT * FROM [HumanResources].[Shift]

 EXECUTE [dbo].[JUVPROCEDURE2]

 EXEC [dbo].[JUVPROCEDURE2]

 ----DELETE PROCEDURES
 
 DROP PROC [dbo].[JUVPROCEDURE]

 ---PARAMETRIZED PROCEDURE

 CREATE PROC MYFIRSTPARAMPROC
 @PARAM_NAME VARCHAR(50)
 AS
 SET NOCOUNT ON
 SELECT * FROM [HumanResources].[Shift]
 WHERE NAME = @PARAM_NAME

 EXEC [dbo].[MYFIRSTPARAMPROC] @PARAM_NAME='DAY'
 EXEC [dbo].[MYFIRSTPARAMPROC] 'DAY'

 DROP PROC MYFIRSTPARAMPROC

 CREATE PROC MYFIRSTPARAMPROC
 @PARAM_NAME VARCHAR(50) = 'EVENING'
 AS
 SET NOCOUNT ON
 SELECT * FROM [HumanResources].[Shift]
 WHERE NAME = @PARAM_NAME

 EXEC [dbo].[MYFIRSTPARAMPROC] 'DAY'

 ---OUTPUT VALUE AS RESULT PROCEDURE

 CREATE PROCEDURE MYFIRSTOUTPUTSP
 @TOPSHIFT VARCHAR(50) OUTPUT
 AS
 SET @TOPSHIFT =(SELECT TOP (1) SHIFTID FROM [HumanResources].[Shift])

 DECLARE @OUTPUTRESULT VARCHAR(50)
 EXEC MYFIRSTOUTPUTSP @OUTPUTRESULT OUTPUT
 SELECT @OUTPUTRESULT